In [39]:
"""
View parquet file as DataFrame using Polars
"""

import polars as pl
from pathlib import Path

# Read the latest parquet file
file_path = "/Users/hieudt/edgar-analysis-project/outputs"

# Read file using Polars
df = pl.read_parquet(file_path)

# Display data
df

shape: (6_878, 8)
┌──────┬─────────┬──────────────┬────────────┬────────────┬───────────┬──────────────┬─────────────┐
│ year ┆ quarter ┆ filename     ┆ cik        ┆ filed_date ┆ form_type ┆ conformed_pe ┆ item_1a     │
│ ---  ┆ ---     ┆ ---          ┆ ---        ┆ ---        ┆ ---       ┆ riod         ┆ ---         │
│ str  ┆ str     ┆ str          ┆ str        ┆ str        ┆ str       ┆ ---          ┆ str         │
│      ┆         ┆              ┆            ┆            ┆           ┆ str          ┆             │
╞══════╪═════════╪══════════════╪════════════╪════════════╪═══════════╪══════════════╪═════════════╡
│ 2024 ┆ QTR2    ┆ 20240627_10- ┆ 0001630113 ┆ 20240627   ┆ 10-K      ┆ 20240331     ┆ ITEM        │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ 1A. RISK    │
│      ┆         ┆ _16301…      ┆            ┆            ┆           ┆              ┆ FACTORS     │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆             │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ Risks       │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ …           │
│ 2024 ┆ QTR2    ┆ 20240415_10- ┆ 0001814215 ┆ 20240415   ┆ 10-K      ┆ 20231231     ┆ Item 1A     │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ Risk        │
│      ┆         ┆ _18142…      ┆            ┆            ┆           ┆              ┆ Factors in  │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ this A…     │
│ 2024 ┆ QTR2    ┆ 20240510_10- ┆ 0000065596 ┆ 20240510   ┆ 10-K      ┆ 20231231     ┆ Item        │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ 1A Risk     │
│      ┆         ┆ _65596…      ┆            ┆            ┆           ┆              ┆ Factors,    │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ and         │
│ 2024 ┆ QTR2    ┆ 20240405_10- ┆ 0001966734 ┆ 20240405   ┆ 10-K      ┆ 20231231     ┆ null        │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆             │
│      ┆         ┆ _19667…      ┆            ┆            ┆           ┆              ┆             │
│ 2024 ┆ QTR2    ┆ 20240401_10- ┆ 0001568969 ┆ 20240401   ┆ 10-K      ┆ 20231231     ┆ ITEM        │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ 1A. RISK    │
│      ┆         ┆ _15689…      ┆            ┆            ┆           ┆              ┆ FACTORS     │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆             │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ Invest…     │
│ …    ┆ …       ┆ …            ┆ …          ┆ …          ┆ …         ┆ …            ┆ …           │
│ 2024 ┆ QTR1    ┆ 20240322_10- ┆ 0001838615 ┆ 20240322   ┆ 10-K      ┆ 20231231     ┆ Item 1A.    │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ Employees   │
│      ┆         ┆ _18386…      ┆            ┆            ┆           ┆              ┆  As of Dec… │
│ 2024 ┆ QTR1    ┆ 20240124_10- ┆ 0001173420 ┆ 20240124   ┆ 10-K      ┆ 20231130     ┆ Item 1A,    │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ Risk        │
│      ┆         ┆ _11734…      ┆            ┆            ┆           ┆              ┆ Factors ,   │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ below.…     │
│ 2024 ┆ QTR1    ┆ 20240226_10- ┆ 0000879101 ┆ 20240226   ┆ 10-K      ┆ 20231231     ┆ Item 1A,    │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ Risk        │
│      ┆         ┆ _19594…      ┆            ┆            ┆           ┆              ┆ Factors and │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ else…       │
│ 2024 ┆ QTR1    ┆ 20240227_10- ┆ 0001127537 ┆ 20240227   ┆ 10-K      ┆ 20231231     ┆ Item 1A     │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ Risk        │
│      ┆         ┆ _11275…      ┆            ┆            ┆           ┆              ┆ Factors and │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆ elsew…      │
│ 2024 ┆ QTR1    ┆ 20240223_10- ┆ 0000091882 ┆ 20240223   ┆ 10-K      ┆ 20231231     ┆ Item 1A.    │
│      ┆         ┆ K_edgar_data ┆            ┆            ┆           ┆              ┆ Risk        │
│      ┆         ┆ _91882…      ┆            ┆            ┆           ┆              ┆ Factors     │
│      ┆         ┆              ┆            ┆            ┆           ┆              ┆  DESC s…    │
└──────┴─────────┴──────────────┴────────────┴────────────┴───────────┴──────────────┴─────────────┘

In [40]:
df.filter(pl.col('item_1a').is_null())

shape: (116, 8)
┌──────┬─────────┬────────────────┬────────────┬────────────┬───────────┬────────────────┬─────────┐
│ year ┆ quarter ┆ filename       ┆ cik        ┆ filed_date ┆ form_type ┆ conformed_peri ┆ item_1a │
│ ---  ┆ ---     ┆ ---            ┆ ---        ┆ ---        ┆ ---       ┆ od             ┆ ---     │
│ str  ┆ str     ┆ str            ┆ str        ┆ str        ┆ str       ┆ ---            ┆ str     │
│      ┆         ┆                ┆            ┆            ┆           ┆ str            ┆         │
╞══════╪═════════╪════════════════╪════════════╪════════════╪═══════════╪════════════════╪═════════╡
│ 2024 ┆ QTR2    ┆ 20240405_10-K_ ┆ 0001966734 ┆ 20240405   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_196 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 67…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR2    ┆ 20240416_10-K_ ┆ 0000356590 ┆ 20240416   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_356 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 59…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR2    ┆ 20240416_10-K_ ┆ 0001714562 ┆ 20240416   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_171 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 45…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR2    ┆ 20240621_10-K_ ┆ 0001985449 ┆ 20240621   ┆ 10-K      ┆ 20240331       ┆ null    │
│      ┆         ┆ edgar_data_198 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 54…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR2    ┆ 20240621_10-K_ ┆ 0001962487 ┆ 20240621   ┆ 10-K      ┆ 20240331       ┆ null    │
│      ┆         ┆ edgar_data_196 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 24…            ┆            ┆            ┆           ┆                ┆         │
│ …    ┆ …       ┆ …              ┆ …          ┆ …          ┆ …         ┆ …              ┆ …       │
│ 2024 ┆ QTR1    ┆ 20240314_10-K_ ┆ 0001395585 ┆ 20240314   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_139 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 55…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR1    ┆ 20240320_10-K_ ┆ 0001830316 ┆ 20240320   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_183 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 03…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR1    ┆ 20240223_10-K_ ┆ 0001295810 ┆ 20240223   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_129 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 58…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR1    ┆ 20240321_10-K_ ┆ 0000315958 ┆ 20240321   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_315 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 95…            ┆            ┆            ┆           ┆                ┆         │
│ 2024 ┆ QTR1    ┆ 20240322_10-K_ ┆ 0001128250 ┆ 20240322   ┆ 10-K      ┆ 20231231       ┆ null    │
│      ┆         ┆ edgar_data_112 ┆            ┆            ┆           ┆                ┆         │
│      ┆         ┆ 82…            ┆            ┆            ┆           ┆                ┆         │
└──────┴─────────┴────────────────┴────────────┴────────────┴───────────┴────────────────┴─────────┘

In [32]:
df_null = df.filter(pl.col('item_1a').is_null())
df_null['filename'][10]

'20240621_10-K_edgar_data_1976562_0000950170-24-076192.txt'

In [33]:
df['item_7'][0]

'7_'